import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, rm, readdir } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import sharp from 'sharp';
import { createCoverStorage } from '../server/cover-storage.mjs';
import { createPresentationService } from '../server/presentation-service.mjs';
import { createCollectionService } from '../server/collection-service.mjs';
import { createWishlistService } from '../server/wishlist-service.mjs';
import { createWriteQueue } from '../server/record-operations.mjs';
import { recordRevision } from '../src/collection-record.mjs';
import { wishlistRevision } from '../src/wishlist-record.mjs';
import { record } from './fixtures/collection.mjs';
import { wish, memoryRepository } from './fixtures/wishlist.mjs';
for(const section of ['collection','wishlist'])test(`initial Add ${section}: canonical image pipeline, no wrong references or assets after rejection`,async t=>{
 const directory=await mkdtemp(join(tmpdir(),'vinyl-add-cover-'));t.after(()=>rm(directory,{recursive:true,force:true}));
 const collection=memoryRepository([], 'collection'),wishlist=memoryRepository([]),serial=createWriteQueue();
 const covers=createCoverStorage(directory),presentation=createPresentationService({collection,wishlist,covers,serial});
 const source=section==='collection'?record:wish;
 const {id,coverId,favorite,...draft}=source;
 const service=section==='collection'?createCollectionService(collection,serial):createWishlistService(wishlist,collection,serial);
 const create=section==='collection'?service.createRecord:service.createWishlistRecord;
 const repo=section==='collection'?collection:wishlist,revision=section==='collection'?recordRevision:wishlistRevision;
 const created=await create(draft);assert.equal(created.coverId,null);
 await assert.rejects(presentation.changeCover(section,created.id,await revision(created),Buffer.from('invalid image')), {message:'INVALID_COVER'});
 assert.equal((await repo.read()).length,1);assert.equal((await repo.read())[0].coverId,null);assert.deepEqual(await readdir(directory),[]);
 const bytes=await sharp({create:{width:32,height:32,channels:3,background:'#987654'}}).png().toBuffer();
 const covered=await presentation.changeCover(section,created.id,await revision(created),bytes);
 assert.equal(covered.id,created.id);assert.ok(covered.coverId);assert.equal((await repo.read())[0].coverId,covered.coverId);
 assert.deepEqual((await readdir(directory)).filter(name=>name!=='.holds'),[covered.coverId]);
 assert.deepEqual(await readdir(join(directory,'.holds')),[]);
 assert.equal(repo.writes.some(w=>w[0]==='delete'),false);
});
