CREATE TABLE vinyl.login_reservations (
  login_normalized text PRIMARY KEY CHECK (login_normalized ~ '^[a-z][a-z0-9_-]{2,29}$'),
  reserved_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE vinyl.users (
  id uuid PRIMARY KEY,
  login text NOT NULL,
  login_normalized text NOT NULL UNIQUE REFERENCES vinyl.login_reservations(login_normalized),
  email text NOT NULL,
  email_normalized text NOT NULL UNIQUE,
  full_name text,
  collection_public boolean NOT NULL DEFAULT false,
  wishlist_public boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK (login = login_normalized),
  CHECK (email = btrim(email) AND email_normalized = lower(email COLLATE "C")),
  CHECK (email ~ '^[!-~]+@[a-zA-Z0-9.-]+$')
);
CREATE TABLE vinyl.covers (
  id uuid PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES vinyl.users(id) ON DELETE RESTRICT,
  storage_key text NOT NULL UNIQUE,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, id),
  CHECK (storage_key = id::text)
);
CREATE TABLE vinyl.collection_records (
  id uuid PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES vinyl.users(id) ON DELETE CASCADE,
  artist text NOT NULL CHECK (length(btrim(artist)) > 0),
  album text NOT NULL CHECK (length(btrim(album)) > 0),
  genre text, additional_genre text, label text,
  album_year text NOT NULL CHECK (album_year ~ '^[0-9]{4}$'),
  record_year text CHECK (record_year ~ '^[0-9]{4}$'),
  edition_type text CHECK (edition_type IN ('Оригинал', 'Переиздание')),
  note text,
  -- ISO string preserves the existing JS calendar contract, including year 0000.
  purchase_date text CHECK (purchase_date ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}$'),
  purchase_store text,
  purchase_price numeric CHECK (purchase_price >= 0 AND purchase_price NOT IN ('NaN'::numeric, 'Infinity'::numeric, '-Infinity'::numeric)),
  cover_id uuid,
  favorite boolean NOT NULL DEFAULT false,
  revision text NOT NULL CHECK (revision ~ '^"[a-f0-9]{64}"$'),
  version bigint NOT NULL DEFAULT 1 CHECK (version > 0),
  position bigint GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  FOREIGN KEY (user_id, cover_id) REFERENCES vinyl.covers(user_id, id) ON DELETE RESTRICT
);
CREATE TABLE vinyl.wishlist_records (
  id uuid PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES vinyl.users(id) ON DELETE CASCADE,
  artist text NOT NULL CHECK (length(btrim(artist)) > 0),
  album text NOT NULL CHECK (length(btrim(album)) > 0),
  genre text, additional_genre text, label text,
  album_year text NOT NULL CHECK (album_year ~ '^[0-9]{4}$'),
  record_year text CHECK (record_year ~ '^[0-9]{4}$'),
  edition_type text CHECK (edition_type IN ('Оригинал', 'Переиздание')),
  note text, store_url text, cover_id uuid,
  revision text NOT NULL CHECK (revision ~ '^"[a-f0-9]{64}"$'),
  version bigint NOT NULL DEFAULT 1 CHECK (version > 0),
  position bigint GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  FOREIGN KEY (user_id, cover_id) REFERENCES vinyl.covers(user_id, id) ON DELETE RESTRICT
);
-- Loaded records keep source order for stable JS Artist/Year sorting and CSV ties.
CREATE INDEX collection_owner_order ON vinyl.collection_records(user_id, position, id);
CREATE INDEX wishlist_owner_order ON vinyl.wishlist_records(user_id, position, id);
-- FK/reference checks and orphan inspection, not image search.
CREATE INDEX collection_cover ON vinyl.collection_records(user_id, cover_id) WHERE cover_id IS NOT NULL;
CREATE INDEX wishlist_cover ON vinyl.wishlist_records(user_id, cover_id) WHERE cover_id IS NOT NULL;
CREATE TABLE vinyl.data_imports (
  import_key text PRIMARY KEY,
  manifest_hash text NOT NULL CHECK (manifest_hash ~ '^[a-f0-9]{64}$'),
  user_id uuid NOT NULL UNIQUE REFERENCES vinyl.users(id) ON DELETE CASCADE,
  report jsonb NOT NULL,
  completed_at timestamptz NOT NULL DEFAULT now()
);
